export const FINE_SETTING_KEYS = {
  OVERDUE_FEE_PER_DAY: 'OVERDUE_FEE_PER_DAY',

  DAMAGED_BOOK_FINE_MODE: 'DAMAGED_BOOK_FINE_MODE',
  DAMAGED_BOOK_FINE_FIXED: 'DAMAGED_BOOK_FINE_FIXED',

  DAMAGED_BOOK_FINE_PERCENT: 'DAMAGED_BOOK_FINE_PERCENT',

  LOST_BOOK_FINE_MODE: 'LOST_BOOK_FINE_MODE',

  LOST_BOOK_REIMBURSE_PERCENT: 'LOST_BOOK_REIMBURSE_PERCENT',
  LOST_BOOK_PROCESSING_FEE: 'LOST_BOOK_PROCESSING_FEE',
  LOST_BOOK_OVERDUE_DAYS_AS_LOST: 'LOST_BOOK_OVERDUE_DAYS_AS_LOST',

  RENEWAL_FEE_AMOUNT: 'RENEWAL_FEE_AMOUNT',
} as const;

export const DEFAULT_OVERDUE_FEE_PER_DAY = 5000;

export const DEFAULT_DAMAGED_BOOK_FINE_MODE = 'fixed' as const;
export const DEFAULT_DAMAGED_BOOK_FINE_FIXED = 50_000;
export const DEFAULT_DAMAGED_BOOK_FINE_PERCENT = 30;

export const DEFAULT_LOST_BOOK_FINE_MODE = 'percent' as const;

export const DEFAULT_LOST_BOOK_REIMBURSE_PERCENT = 150;
export const DEFAULT_LOST_BOOK_PROCESSING_FEE = 20_000;
export const DEFAULT_LOST_BOOK_OVERDUE_DAYS_AS_LOST = 30;

export const DEFAULT_RENEWAL_FEE_AMOUNT = 10_000;
