version: '3.8'

services:
  postgres:
    container_name: nestjs_qltv_db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai_service
    ports:
      - '11235:11235'
    shm_size: '1gb'
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    ports:
      - '5672:5672' # Cổng AMQP để Backend NestJS kết nối
      - '15672:15672' # Cổng Dashboard UI quản lý trực quan
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - '6379:6379'
    restart: unless-stopped
volumes:
  postgres_data:
